export const RABBIT_BREEDS = [
  {name:'アメリカン', code:'AM', origin:'アメリカ', length:'約45〜55cm', weight:'約4.1〜5.4kg', features:['大型寄り','マンドリン型の体型','穏やかな気質']},
  {name:'アメリカンチンチラ', code:'AC', origin:'アメリカ', length:'約45〜55cm', weight:'約4.1〜5.4kg', features:['チンチラカラー','がっしり体型','希少性が高い']},
  {name:'アメリカンファジーロップ', code:'AF', origin:'アメリカ', length:'約30〜35cm', weight:'約1.4〜1.8kg', features:['垂れ耳','ふわふわの長毛','小柄で愛らしい']},
  {name:'アメリカンセーブル', code:'AS', origin:'アメリカ', length:'約38〜45cm', weight:'約3.2〜4.5kg', features:['セーブル色','濃淡のある被毛','落ち着いた印象']},
  {name:'アルジャンテブラン', code:'AB', origin:'フランス', length:'約40〜50cm', weight:'約3.6〜4.8kg', features:['銀がかったチョコレート色','短毛','カナダ由来']},
  {name:'ベルジアンヘア', code:'BH', origin:'ベルギー', length:'約45〜55cm', weight:'約3.6〜4.3kg', features:['野うさぎ風の体型','長い脚','活動的']},
  {name:'ベファレン', code:'BV', origin:'ベルギー', length:'約45〜55cm', weight:'約3.6〜5.4kg', features:['大きめの体','光沢のある被毛','青い目の白色も有名']},
  {name:'ブランデホト', code:'BD', origin:'フランス', length:'約40〜50cm', weight:'約3.6〜5.0kg', features:['白い体','黒いアイバンド','上品な見た目']},
  {name:'ブルーホリサー', code:'BL', origin:'アメリカ', length:'約35〜45cm', weight:'約2.5〜3.3kg', features:['スチールブルーの被毛','円筒型の体型','2023年にARBA公認']},
  {name:'ブリタニアペティート', code:'BP', origin:'イギリス', length:'約20〜28cm', weight:'約0.7〜1.1kg', features:['とても小柄','弓なりの体型','活発で機敏']},
  {name:'カリフォルニアン', code:'CA', origin:'アメリカ', length:'約45〜55cm', weight:'約4.1〜4.8kg', features:['白地に黒いポイント','赤い目','しっかりした体']},
  {name:'シャンパーニュダルジャン', code:'CD', origin:'フランス', length:'約45〜55cm', weight:'約4.1〜5.4kg', features:['銀色の被毛','生まれた時は黒っぽい','歴史ある品種']},
  {name:'チェッカードジャイアント', code:'CG', origin:'ドイツ／フランス', length:'約60〜75cm', weight:'約5.0〜7.0kg以上', features:['大型','斑点模様','半アーチ体型']},
  {name:'シナモン', code:'CN', origin:'アメリカ', length:'約45〜55cm', weight:'約4.5〜5.0kg', features:['シナモン色','商業型の体型','比較的新しい品種']},
  {name:'クリームダルジャン', code:'CR', origin:'フランス', length:'約40〜50cm', weight:'約3.6〜5.0kg', features:['クリーム色','オレンジの下毛','希少品種']},
  {name:'チェコフロスティ', code:'CF', origin:'チェコ', length:'約32〜40cm', weight:'約2.5〜3.6kg', features:['霜がかった白い被毛','黒っぽい目元','コンパクト']},
  {name:'ダッチ', code:'DU', origin:'オランダ', length:'約30〜38cm', weight:'約1.6〜2.5kg', features:['特徴的な白黒模様','小〜中型','人に慣れやすい']},
  {name:'ドワーフホト', code:'DH', origin:'ドイツ', length:'約22〜28cm', weight:'約0.9〜1.4kg', features:['黒いアイライン','小柄','白い体']},
  {name:'ドワーフパピヨン', code:'DP', origin:'フランス', length:'約25〜32cm', weight:'約1.4〜2.0kg', features:['蝶のような鼻模様','斑点模様','小型のスポット系']},
  {name:'イングリッシュアンゴラ', code:'EA', origin:'イギリス', length:'約30〜38cm', weight:'約2.3〜3.4kg', features:['顔まわりまで長毛','羊毛のような被毛','こまめな手入れが必要']},
  {name:'イングリッシュロップ', code:'EL', origin:'イギリス', length:'約45〜60cm', weight:'約4.5kg以上', features:['非常に長い垂れ耳','歴史あるロップ','ゆったりした印象']},
  {name:'イングリッシュスポット', code:'ES', origin:'イギリス', length:'約38〜48cm', weight:'約2.3〜3.6kg', features:['スポット模様','すらっとした体型','活発']},
  {name:'フレミッシュジャイアント', code:'FG', origin:'ベルギー', length:'約60〜75cm', weight:'約6.0〜10.0kg以上', features:['超大型','温厚','広い飼育スペースが必要']},
  {name:'フロリダホワイト', code:'FW', origin:'アメリカ', length:'約35〜42cm', weight:'約1.8〜2.7kg', features:['白い短毛','赤い目','コンパクトで丸い体']},
  {name:'フレンチアンゴラ', code:'FA', origin:'フランス', length:'約40〜50cm', weight:'約3.4〜4.8kg', features:['長毛','顔まわりは比較的すっきり','毛質が豊か']},
  {name:'フレンチロップ', code:'FL', origin:'フランス', length:'約55〜70cm', weight:'約4.5kg以上', features:['大型の垂れ耳','重量感のある体','穏やか']},
  {name:'ジャイアントアンゴラ', code:'GA', origin:'アメリカ', length:'約50〜65cm', weight:'約4.3kg以上', features:['大型の長毛種','白い被毛が代表的','毛量が多い']},
  {name:'ジャイアントチンチラ', code:'GC', origin:'アメリカ', length:'約55〜70cm', weight:'約5.4〜7.3kg', features:['大型','チンチラカラー','がっしりした体']},
  {name:'ハーレクイン', code:'HQ', origin:'フランス', length:'約38〜48cm', weight:'約2.9〜4.3kg', features:['左右で分かれる模様','個性的な配色','ショー映えする']},
  {name:'ハバナ', code:'HV', origin:'オランダ', length:'約30〜38cm', weight:'約2.0〜2.9kg', features:['光沢のある被毛','コンパクト','丸みのある体']},
  {name:'ヒマラヤン', code:'HM', origin:'起源諸説あり（英国で標準化）', length:'約30〜40cm', weight:'約1.1〜2.0kg', features:['ポイントカラー','細長い体型','落ち着いた雰囲気']},
  {name:'ホーランドロップ', code:'HL', origin:'オランダ', length:'約30〜35cm', weight:'約1.3〜1.8kg', features:['垂れ耳','丸い顔','穏やかで人懐っこい']},
  {name:'ジャージーウーリー', code:'JW', origin:'アメリカ', length:'約25〜30cm', weight:'約1.0〜1.6kg', features:['小型の長毛種','丸い体','おだやか']},
  {name:'ライラック', code:'LI', origin:'イギリス', length:'約35〜45cm', weight:'約2.5〜3.6kg', features:['淡いラベンダー色','中型','やわらかな印象']},
  {name:'ライオンヘッド', code:'LH', origin:'ベルギー', length:'約25〜35cm', weight:'約1.2〜1.7kg', features:['たてがみ状の毛','小型','個性的な見た目']},
  {name:'ミニカリフォルニアン', code:'MC', origin:'アメリカ', length:'約35〜45cm', weight:'約2.7kg以下', features:['カリフォルニアンの小型版','白地にポイントカラー','ARBA第53番目の公認品種']},
  {name:'ミニロップ', code:'ML', origin:'ドイツ', length:'約35〜45cm', weight:'約2.0〜3.0kg', features:['垂れ耳','丸くがっしりした体','親しみやすい']},
  {name:'ミニレッキス', code:'MR', origin:'アメリカ', length:'約30〜35cm', weight:'約1.4〜2.0kg', features:['ベルベットのような毛質','短毛','小柄']},
  {name:'ミニサテン', code:'MS', origin:'アメリカ', length:'約30〜38cm', weight:'約1.4〜2.2kg', features:['光沢のある被毛','小型','なめらかな手触り']},
  {name:'ネザーランドドワーフ', code:'ND', origin:'オランダ', length:'約20〜28cm', weight:'約0.8〜1.2kg', features:['小柄','短い耳','活発で好奇心旺盛']},
  {name:'ニュージーランド', code:'NZ', origin:'アメリカ', length:'約45〜60cm', weight:'約4.0〜5.4kg', features:['大型寄り','しっかりした体','白色が代表的']},
  {name:'パロミノ', code:'PA', origin:'アメリカ', length:'約40〜50cm', weight:'約3.6〜5.0kg', features:['黄金色またはリンクス色','中〜大型','穏やか']},
  {name:'ポーリッシュ', code:'PO', origin:'イギリス', length:'約22〜30cm', weight:'約1.1〜1.6kg', features:['小型','短い耳','丸い頭']},
  {name:'レッキス', code:'RX', origin:'フランス', length:'約40〜50cm', weight:'約3.0〜4.8kg', features:['ベルベット状の被毛','中型','毛並みが特徴的']},
  {name:'ラインランダー', code:'RH', origin:'ドイツ', length:'約40〜50cm', weight:'約2.9〜4.5kg', features:['蝶模様とスポット','白地に色柄','アーチ体型']},
  {name:'サテン', code:'SA', origin:'アメリカ', length:'約40〜50cm', weight:'約3.6〜5.0kg', features:['強い光沢の被毛','なめらか','中〜大型']},
  {name:'サテンアンゴラ', code:'SG', origin:'アメリカ', length:'約38〜50cm', weight:'約3.0〜4.5kg', features:['光沢のある長毛','絹のような質感','手入れが重要']},
  {name:'シルバー', code:'SV', origin:'イギリス', length:'約32〜42cm', weight:'約1.8〜3.2kg', features:['銀差しの被毛','古い歴史','希少性が高い']},
  {name:'シルバーフォックス', code:'SF', origin:'アメリカ', length:'約45〜55cm', weight:'約4.1〜5.4kg', features:['銀毛の入る被毛','大型寄り','毛が立ちやすい']},
  {name:'シルバーマーチン', code:'SM', origin:'アメリカ', length:'約32〜42cm', weight:'約2.7〜4.3kg', features:['黒やチョコに白い差し毛','コントラストが強い','中型']},
  {name:'スタンダードチンチラ', code:'SC', origin:'フランス', length:'約35〜45cm', weight:'約2.3〜3.4kg', features:['チンチラカラー','中型','丸みのある体']},
  {name:'タン', code:'TA', origin:'イギリス', length:'約30〜38cm', weight:'約1.8〜2.7kg', features:['黒や青にタン模様','小〜中型','活発']},
  {name:'トリアンタ', code:'TH', origin:'オランダ', length:'約30〜38cm', weight:'約2.0〜2.7kg', features:['鮮やかな赤茶色','コンパクト','温かみのある色']}
];

export function breedByName(name){
  return RABBIT_BREEDS.find(b => b.name === name) || null;
}
export function breedCode(name){
  return breedByName(name)?.code || 'XX';
}
